ALTER TABLE country ADD CONSTRAINT PK_COUNTRY PRIMARY KEY(country_id);
ALTER TABLE city ADD CONSTRAINT PK_CITY PRIMARY KEY(city_id);
ALTER TABLE address ADD CONSTRAINT PK_ADDRESS PRIMARY KEY(address_id);
ALTER TABLE store ADD CONSTRAINT PK_STORE PRIMARY KEY(store_id);
ALTER TABLE customer ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(customer_id);
ALTER TABLE payment ADD CONSTRAINT PK_PAYMENT PRIMARY KEY(payment_id);
ALTER TABLE rental ADD CONSTRAINT PK_RENTAL PRIMARY KEY(rental_id);


ALTER TABLE city ADD CONSTRAINT FK_CITY_COUNTRY FOREIGN KEY(country_id) REFERENCES country(country_id);

ALTER TABLE address ADD CONSTRAINT FK_ADDRESS_CITY FOREIGN KEY(city_id) REFERENCES city(city_id);

ALTER TABLE staff ADD CONSTRAINT PK_STAFF PRIMARY KEY(staff_id);

ALTER TABLE store ADD CONSTRAINT FK_STORE_MANAGER FOREIGN KEY(manager_staff_id) REFERENCES staff(staff_id);
ALTER TABLE store ADD CONSTRAINT FK_STORE_ADDRESS FOREIGN KEY(address_id) REFERENCES address(address_id);

ALTER TABLE staff ADD CONSTRAINT FK_STAFF_ADDRESS FOREIGN KEY(address_id) REFERENCES address(address_id);
ALTER TABLE staff ADD CONSTRAINT FK_STAFF_STORE FOREIGN KEY(store_id) REFERENCES store(store_id);

ALTER TABLE customer ADD CONSTRAINT FK_CUSTOMER_STORE FOREIGN KEY(store_id) REFERENCES store(store_id);
ALTER TABLE customer ADD CONSTRAINT FK_CUSTOMER_ADDRESS FOREIGN KEY(address_id) REFERENCES address(address_id);

ALTER TABLE inventory ADD CONSTRAINT PK_INVENTORY PRIMARY KEY(inventory_id);
ALTER TABLE inventory ADD CONSTRAINT FK_INVENTORY_STORE FOREIGN KEY(store_id) REFERENCES store(store_id);
--ALTER TABLE inventory ADD CONSTRAINT FK_INVENTORY_RENTAL FOREIGN KEY(film_id) REFERENCES rental(rental_id);

ALTER TABLE payment ADD CONSTRAINT FK_PAYMENT_CUSTOMER FOREIGN KEY(customer_id) REFERENCES customer(customer_id);
ALTER TABLE payment ADD CONSTRAINT FK_PAYMENT_STAFF FOREIGN KEY(staff_id) REFERENCES staff(staff_id);
ALTER TABLE payment ADD CONSTRAINT FK_PAYMENT_RENTAL FOREIGN KEY(rental_id) REFERENCES rental(rental_id);

ALTER TABLE rental ADD CONSTRAINT FK_RENTAL_INVENTORY FOREIGN KEY(inventory_id) REFERENCES inventory(inventory_id);
ALTER TABLE rental ADD CONSTRAINT FK_RENTAL_CUSTOMER FOREIGN KEY(customer_id) REFERENCES customer(customer_id);
ALTER TABLE rental ADD CONSTRAINT FK_RENTAL_STAFF FOREIGN KEY(staff_id) REFERENCES staff(staff_id);